[package]
name = "protolok"
description = "Custom internet protocol for Loki."
authors = ["The Loki Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
base16ct = "0.2"
once_cell = "1.17.1"
rand = "0.8.5"
rsa = "0.8"
sha2 = "0.10"
