[package]
name = "loki-keyserver"
description = "Federated keyserver for Loki"
authors = ["The Loki Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
loki-shared = { path = "../loki-shared" }
protolok = { path = "../protolok" }
