[package]
name = "loki-server"
description = "Backend for the Loki chat app."
authors = ["The Loki Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
loki-shared = { path = "../loki-shared" }
protolok = { path = "../protolok" }
tokio = { version = "1", features = ["full"] }
