[package]
name = "lokui"
description = "GUI framework for Loki."
authors = ["The Loki Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { version = "0.60.0", features = ["gl"] }
miniquad = { git = "https://github.com/loki-chat/lokinit" }
