[package]
name = "lokui"
description = "GUI framework for Loki."
authors = ["The Loki Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
miniquad = { path = "../../lokinit" }
lokui-macros = { path = "../lokui-macros" }
skia-safe = { version = "0.60.0" }
